### ISSUE TITLE
disable debug

### ISSUE THREAD

**Issue by YouSour** [wendellrocha/enhanced_meteorify#2]
hi , how can i disable debug ?

**Comment by wendellrocha** [comment]
I did not understand

**Comment by YouSour** [comment]
@wendellrocha what i mean text in console 
```
[DDP] <- :: {"msg":"ping"}
[DDP] -> :: {"msg":"pong"}
[DDP] <- :: {"msg":"ping"}
[DDP] -> :: {"msg":"pong"}
```

**Comment by wendellrocha** [comment]
Oh ok. It is currently not possible to disable logging. But I can work on a `log: true|false` for Meteor.connect.

It may take a while to make this change because I'm out of time. Once I have the change, I'll let you know.

**Comment by YouSour** [comment]
@wendellrocha thank you for your time , bro , i wait for it

**Comment by wendellrocha** [comment]
@YouSour 

[Release 3.0.2](https://pub.dev/packages/enhanced_meteorify/changelog)

Suppress all info and warn logs.

```dart
   await Meteor.connect(
      'ws://' + Constants.URL_SERVIDOR + '/websocket',
      reconnectInterval: Duration(seconds: 1),
      autoLoginOnReconnect: true,
      enableLogs: false,
    );
```

**Comment by YouSour** [comment]
@wendellrocha noted , thank you 😄
