### ISSUE TITLE
Automatic reconnect after Meteor.disconnect()

### ISSUE THREAD

**Issue by ruerob** [wendellrocha/enhanced_meteorify#4]
Hello @wendellrocha!

I've got a small problem here. I have a disconnect button in my app. That should disconnect the app from the server until the user wants to reconnect.
The disconnect seems to work at first. But then I get a message into my logging:

```
I/flutter ( 6904): [DDP] <- :: {"msg":"ping"}
I/flutter ( 6904): [DDP] -> :: {"msg":"pong"}
I/flutter ( 6904): [DDP] <- :: {"msg":"ping"}
I/flutter ( 6904): [DDP] :: Disconnect due to websocket onDone
I/flutter ( 6904): [DDP] :: Disconnected code: null, reason: null
I/flutter ( 6904): [DDP] :: Schedule reconnect due to websocket onDone
```
And after some more seconds and ping pongs, the app reconnects to the server.

I tested the disconnect in a new dart project. I just called the following function before building the first view:

```
  static _connect() async{
    await Meteor.connect("ws://bladereport-dev.rc-srv.de/websocket");

    Meteor.disconnect();
  }
```

I already tried to locate the problem but wasn't able to make a pull request for now.

I hope this issue helps you.

Have a great day
Robert

**Comment by wendellrocha** [comment]
I'll look and as soon as I have a solution, I'll let you know.

**Comment by wendellrocha** [comment]
@ruerob fixed issue in version 3.0.3!

When using `Meteor.disconnect()`, the socket received null as a value but the listen still alive, so the reconnect was scheduled. In this new version, the socket is closed and there is a check if it was manually disconnected before scheduling the reconnection.

**Comment by ruerob** [comment]
Whoa! That was fast! Thank you! I'll test it right now!

**Comment by ruerob** [comment]
It works now. The only thing that still looks like a connection is the:

```
I/flutter ( 7197): [DDP] <- :: {"msg":"ping"}
I/flutter ( 7197): [DDP] -> :: {"msg":"pong"}
```

But that is a minor bug I think.

Thank you for the fast reply and the fast fix!

**Comment by wendellrocha** [comment]
@ruerobIt didn't happen to me. Ping-pong only happens after reconnect.

```
I/flutter (19075): 2021-07-06T11:27:51.855631
I/flutter (19075): ConnectionStatus.DISCONNECTED
I/flutter (19075): 2021-07-06T11:47:07.551285
I/flutter (19075): [DDP] -> :: {"msg":"connect","version":"1","support":["1","pre2","pre1"],"session":"a4EfKjEEwSHXSNniS"}
I/flutter (19075): [DDP] <- :: {"testMessageOnConnect":true}
I/flutter (19075): [DDP] ! :: Server send message to test connection. Message: {testMessageOnConnect: true}
I/flutter (19075): [DDP] <- :: {"msg":"connected","session":"Ny3PvKp8cWDuNKCZE"}
I/flutter (19075): ConnectionStatus.CONNECTED
I/flutter (19075): [DDP] <- :: {"msg":"ping"}
I/flutter (19075): [DDP] -> :: {"msg":"pong"}
```
