### ISSUE TITLE
Unhandled Exception: type 'Future<String>' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by davinderkumar** [wendellrocha/enhanced_meteorify#6]
I tried using few methods like Accounts.changePassword, Accounts.createUser with return type String, they all throw this exception:
Unhandled Exception: type 'Future<String>' is not a subtype of type 'String' in type cast

**Comment by wendellrocha** [comment]
Version 3.1.0 available on pub.dev!

I rewrote the account methods. Now you can access them using the Meteor class.
Meteor.createUser, Meteor.changePassword...

_I'm running out of time to work on the package. Pull requests are welcome!_
