### ISSUE TITLE
Question: re-subscribe same name with different arguments

### ISSUE THREAD

**Issue by joyjiyuan** [wendellrocha/enhanced_meteorify#7]
> Technically, what happens when one of these reactive sources changes is the following:

> 1. The reactive data source invalidates the autorun computation (marks it so that it re-runs in the next Tracker flush cycle).
> 2. The subscription detects this, and given that anything is possible in next computation run, marks itself for destruction.
> 3. The computation re-runs, with .subscribe() being re-called either with the same or different arguments.
> 4. If the subscription is run with the same arguments then the “new” subscription discovers the old “marked for destruction” subscription that’s sitting around, with the same data already ready, and reuses that.
> 5. If the subscription is run with different arguments, then a new subscription is created, which connects to the publication on the server.
> 6. At the end of the flush cycle (i.e. after the computation is done re-running), the old subscription checks to see if it was re-used, and if not, sends a message to the server to tell the server to shut it down.

> Step 4 above is an important detail—that the system cleverly knows not to re-subscribe if the autorun re-runs and subscribes with the exact same arguments. This holds true even if the new subscription is set up somewhere else in the template hierarchy. For example, if a user navigates between two pages that both subscribe to the exact same subscription, the same mechanism will kick in and no unnecessary subscribing will happen.

Does the package implements this mechanism?

When I re-subscribe same name with different arguments which one is better performance? unsubscribe first or just resubscribe?

Thanks

**Comment by wendellrocha** [comment]
Unfortunately the package does not implement Tracker.
I recommend doing the unsubscribe and resubscribe with the arguments updated so that the previous subscribe doesn't remain active/in memory.

**Comment by joyjiyuan** [comment]
Thank you for reply. I will follow your recommendation.
