### ISSUE TITLE
userAsMap is not defined

### ISSUE THREAD

**Issue by joyjiyuan** [wendellrocha/enhanced_meteorify#8]
can't find userAsMap in code but document.

**Comment by wendellrocha** [comment]
Hi, I removed the method but forgot to update the documentation. Particularly I don't use the user document that Meteor returns, I prefer to have a published _loggedUser_ with the necessary information (name, email, profile picture, date of birth, etc).

If you think _userAsMap_ is interesting or necessary, pull requests are welcome.

**Comment by joyjiyuan** [comment]
OK. I will call backend method instead. Thank you.
